# To build and deploy to Cloud Run, run from this directory:
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/whats-the-word', '.']
  dir: 'app'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/whats-the-word']
  dir: 'app'
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'whats-the-word', '--image', 'gcr.io/$PROJECT_ID/whats-the-word', '--region', 'us-east1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/whats-the-word