# To build and deploy to Cloud Run, run from this directory:
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/us-covid-stats', '.']
  dir: 'app'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/us-covid-stats']
  dir: 'app'
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'us-covid-stats', '--image', 'gcr.io/$PROJECT_ID/us-covid-stats', '--region', 'us-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/us-covid-stats