# To build and deploy to Cloud Run, run from this directory:
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
- name: 'gcr.io/$PROJECT_ID/terraform'
  id: terraform init
  args: [
    'init',
    '-backend-config=bucket=$PROJECT_ID-tf-state',
    '-backend-config=prefix=terraform/state'
  ]
  waitFor: ['-']
- name: 'gcr.io/$PROJECT_ID/terraform'
  id: terraform plan
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      # determine terraform changes
      terraform plan > /dev/null \
      -var=google_project_id=$PROJECT_ID \
      -var=google_region=us-east1 \
      -out=tfplan
      
      # write changes (sans color codes) to a file
      terraform show tfplan | sed 's/\x1b\[[0-9;]*m//g' >> /workspace/tfchanges

      # ensure that the changes file was written (the above commands may fail without error)
      if [[ ! -s /workspace/tfchanges ]]; then
        exit 1
      fi

      # add a header to the changes file
      echo -e "Terraform changes from this PR:\n-------------------------------\n$(cat /workspace/tfchanges)" > /workspace/tfchanges

  waitFor: ['terraform init']
- name: 'gcr.io/$PROJECT_ID/github'
  id: publish plan
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      gh auth login --with-token <<< "$$GH_TOKEN"
      gh pr comment $_PR_NUMBER --body-file="/workspace/tfchanges"
  secretEnv: ['GH_TOKEN']
  waitFor: ['terraform plan']
  
availableSecrets:
  secretManager:
    - versionName: projects/940156706176/secrets/github_token/versions/latest
      env: 'GH_TOKEN'